-- DATA DEFINITION LANGUAGE, DDL-- 

/* CREATE A DATABASE */
CREATE DATABASE OXYGEN;

/* USE THE DATABASE */
USE OXYGEN;

/* DELETE A DATABASE */
DROP DATABASE OXYGEN;

/* SHOW LIST OF ALL DATABASES */
SHOW DATABASES;

/* CREATE A TABLE */
CREATE TABLE MARKBOOK (
STUDENT_ID INT, STUDENT_NAME VARCHAR(20), DEPT VARCHAR(255), AGE INT, GENDER CHAR(5),
PERCENT_SCORE INT, REMARK VARCHAR(10)
);

/* ALTER (I.E. EDIT) A TABLE */
ALTER TABLE MARKBOOK ADD EMAIL VARCHAR(255);

/* RENAME A TABLE */
ALTER TABLE MARKBOOK RENAME TO MARKSBOOK;

/* REMOVE ALL ROWS OF A TABLE (N.B. THE TABLE REMAINS INTACT BUT ALL ITS ROWS WILL BE DELETED */
TRUNCATE TABLE MARKSBOOK;

/* DROP AN ENTIRE TABLE */
DROP TABLE MARKSBOOK;

/* DELETE A ROW FROM A TABLE */
DELETE FROM MARKSBOOK WHERE STUDENT_ID = A001;