-- 1. START A TRANSACTION (POSSIBLY TO ENACT CHANGES)
-- MYSQL AND POSTGRESQL
START TRANSACTION;    -- OR
BEGIN;

-- AN EXAMPLE OF A POSSIBLE CHANGE
DELETE FROM TABLE_A WHERE COLUMN_A1 LIKE '%%';

-- SQL SERVER AND SQLITE. (i used /* below to avoid error)
/* BEGIN TRANSACTION;

-- 2. USE COMMIT TO LOCK IN THE CHANGES. YOU CANNOT UNDO (I.E. ROLLBACK) A TRANSACTION ONCE IT HAS BEEN COMMITTED
COMMIT;

-- 3. UNDO CHANGES WITH A ROLLBACK. INSTEAD OF COMMIT (I.E. SAVE IT), ROLLBACK THE CHANGES
ROLLBACK;

